import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  customerSidebar: [
    'customer/what-is-gligle',
    'customer/troubleshooting',
    'customer/ticket-refund',
    // 'customer/faq',
    'customer/support'
    // {
    //   type: 'category',
    //   label: 'Користувачам',
    //   link: {
    //     type: 'generated-index',
    //     title: 'Користувачам',
    //     description: 'Відповідь на постійні питання від користувачів а також пояснення як користуватися сервісом',
    //     slug: 'customer'
    //   },
    //   items: [
    //     'customer/ticket-refund',
    //   ]
    // }

  ],
  organizerSidebar: [
    'organizer/how-to-hold-an-event',
    'organizer/monobank-jars-faq',
    'organizer/how-to-sell-with-telegram',
    'organizer/faq',
    {
      type: 'category',
      label: 'Часті питання',
      link: {
        type: 'generated-index',
        title: 'Часті питання',
        description: 'Відповідь на постійні питання від організаторів а також пояснення як користуватися сервісом',
        slug: 'organizer/faq/'
      },
      items: []
    },
    'organizer/support',
  ],
  legalSidebar: [
    {
      type: 'category',
      label: 'Регламенти',
      // link: {
      //   type: 'generated-index',
      //   title: 'Документи',
      //   description: 'Тут знаходяться усі необхідні документи та регламенти для користувачів та організаторів',
      //   slug: 'legal'
      // },
      items: [
        'legal/general-rules',
        'legal/event-publishing-procedure',
        'legal/telegram-bot-procedure',
        'legal/ticket-buying-procedure',
        'legal/subscription-procedure',
        'legal/organization-verification-procedure',
      ]
    },
    {
      type: 'category',
      label: 'Документи',
      link: {
        type: 'generated-index',
        title: 'Документи',
        description: 'Тут знаходяться усі необхідні документи та регламенти для користувачів та організаторів',
        slug: 'legal'
      },
      items: [
        'legal/public-offer',
        'legal/privacy-policy',
      ]
    },
  ]
};

export default sidebars;
